// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreService.Persistence;

#nullable disable

namespace StoreService.Persistence.Migrations
{
    [DbContext(typeof(StoreServiceDbContext))]
    [Migration("20260302072921_AddDeviceTypeAndDeviceTables")]
    partial class AddDeviceTypeAndDeviceTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoreService.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_type_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("StoreService.Domain.Entities.DeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("device_types", (string)null);
                });

            modelBuilder.Entity("StoreService.Domain.Entities.Device", b =>
                {
                    b.HasOne("StoreService.Domain.Entities.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("StoreService.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("name");

                            b1.HasKey("DeviceId");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("StoreService.Domain.ValueObjects.ImageUrl", "ImageUrl", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_url");

                            b1.HasKey("DeviceId");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("DeviceType");

                    b.Navigation("ImageUrl");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("StoreService.Domain.Entities.DeviceType", b =>
                {
                    b.OwnsOne("StoreService.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("DeviceTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("name");

                            b1.HasKey("DeviceTypeId");

                            b1.ToTable("device_types");

                            b1.WithOwner()
                                .HasForeignKey("DeviceTypeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("StoreService.Domain.Entities.DeviceType", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
